In [1]:
!pip install pandas numpy scikit-learn sentence-transformers gradio kaggle transformers torch

Requirement already satisfied: pandas in c:\users\prince raj\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy in c:\users\prince raj\anaconda3\lib\site-packages (2.1.3)
Requirement already satisfied: scikit-learn in c:\users\prince raj\anaconda3\lib\site-packages (1.6.1)
Requirement already satisfied: sentence-transformers in c:\users\prince raj\anaconda3\lib\site-packages (5.5.1)
Requirement already satisfied: gradio in c:\users\prince raj\anaconda3\lib\site-packages (6.15.1)
Requirement already satisfied: kaggle in c:\users\prince raj\anaconda3\lib\site-packages (2.1.2)
Requirement already satisfied: transformers in c:\users\prince raj\anaconda3\lib\site-packages (5.9.0)
Requirement already satisfied: torch in c:\users\prince raj\anaconda3\lib\site-packages (2.12.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\prince raj\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\prince raj\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\prince raj\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.6.0 in c:\users\prince raj\anaconda3\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\prince raj\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sentence-transformers) (1.16.1)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: packaging>=20.0 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\prince raj\anaconda3\lib\site-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: anyio in c:\users\prince raj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.7.0)
Requirement already satisfied: certifi in c:\users\prince raj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2025.8.3)
Requirement already satisfied: httpcore==1.* in c:\users\prince raj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\prince raj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.7)
Requirement already satisfied: h11>=0.16 in c:\users\prince raj\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: audioop-lts<=0.2.2 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.2.2)
Requirement already satisfied: brotli>=1.1.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.136.3)
Requirement already satisfied: gradio-client==2.5.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (2.5.0)
Requirement already satisfied: groovy~=0.1 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.1.2)
Requirement already satisfied: hf-gradio<1.0,>=0.4.1 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.4.1)
Requirement already satisfied: jinja2<4.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (3.0.2)
Requirement already satisfied: orjson~=3.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (3.11.9)
Requirement already satisfied: pillow<13.0,>=8.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (11.1.0)
Requirement already satisfied: pydantic<=3.0,>=2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (2.10.3)
Requirement already satisfied: pydub<1.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart<1.0,>=0.0.18 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.0.29)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.7 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<2.0,>=0.40.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (1.2.0)
Requirement already satisfied: tomlkit<0.15.0,>=0.12.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.13.2)
Requirement already satisfied: uvicorn>=0.14.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.48.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\prince raj\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.3.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\prince raj\anaconda3\lib\site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\prince raj\anaconda3\lib\site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.4)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\prince raj\anaconda3\lib\site-packages (from pydantic<=3.0,>=2.0->gradio) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in c:\users\prince raj\anaconda3\lib\site-packages (from pydantic<=3.0,>=2.0->gradio) (2.27.1)
Requirement already satisfied: click>=8.2.1 in c:\users\prince raj\anaconda3\lib\site-packages (from typer->transformers) (8.4.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\prince raj\anaconda3\lib\site-packages (from typer->transformers) (1.5.0)
Requirement already satisfied: rich>=13.8.0 in c:\users\prince raj\anaconda3\lib\site-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: bleach in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (6.2.0)
Requirement already satisfied: jupytext in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (1.19.3)
Requirement already satisfied: kagglesdk<1.0,>=0.1.23 in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (0.1.23)
Requirement already satisfied: protobuf in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (6.33.6)
Requirement already satisfied: python-slugify in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: requests in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (2.34.2)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (2.3.0)
Requirement already satisfied: setuptools<82 in c:\users\prince raj\anaconda3\lib\site-packages (from torch) (72.1.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\prince raj\anaconda3\lib\site-packages (from torch) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in c:\users\prince raj\anaconda3\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: colorama in c:\users\prince raj\anaconda3\lib\site-packages (from click>=8.2.1->typer->transformers) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\prince raj\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\prince raj\anaconda3\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\prince raj\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: webencodings in c:\users\prince raj\anaconda3\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: mdit-py-plugins in c:\users\prince raj\anaconda3\lib\site-packages (from jupytext->kaggle) (0.3.0)
Requirement already satisfied: nbformat in c:\users\prince raj\anaconda3\lib\site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\prince raj\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (2.20.0)
Requirement already satisfied: jsonschema>=2.6 in c:\users\prince raj\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (4.23.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\prince raj\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.7.2)
Requirement already satisfied: traitlets>=5.1 in c:\users\prince raj\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (24.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\prince raj\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\prince raj\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\prince raj\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.22.3)
Requirement already satisfied: platformdirs>=2.5 in c:\users\prince raj\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.3.7)
Requirement already satisfied: pywin32>=300 in c:\users\prince raj\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (308)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\prince raj\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\prince raj\anaconda3\lib\site-packages (from requests->kaggle) (3.3.2)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import os
import zipfile
import pandas as pd
import numpy as np

In [3]:
project_path = r"C:\Users\prince raj\ChatBoat For Agriculture"

folders = [
    "datasets",
    "notebooks",
    "models",
    "app",
    "outputs"
]

for folder in folders:
    os.makedirs(os.path.join(project_path, folder), exist_ok=True)

print("Folders Created Successfully")

Folders Created Successfully

In [4]:
!pip install kaggle

Requirement already satisfied: kaggle in c:\users\prince raj\anaconda3\lib\site-packages (2.1.2)
Requirement already satisfied: bleach in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (6.2.0)
Requirement already satisfied: jupytext in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (1.19.3)
Requirement already satisfied: kagglesdk<1.0,>=0.1.23 in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (0.1.23)
Requirement already satisfied: packaging in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (24.2)
Requirement already satisfied: protobuf in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (6.33.6)
Requirement already satisfied: python-dateutil in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: requests in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (2.34.2)
Requirement already satisfied: tqdm in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (2.3.0)
Requirement already satisfied: webencodings in c:\users\prince raj\anaconda3\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in c:\users\prince raj\anaconda3\lib\site-packages (from jupytext->kaggle) (2.2.0)
Requirement already satisfied: mdit-py-plugins in c:\users\prince raj\anaconda3\lib\site-packages (from jupytext->kaggle) (0.3.0)
Requirement already satisfied: nbformat in c:\users\prince raj\anaconda3\lib\site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in c:\users\prince raj\anaconda3\lib\site-packages (from jupytext->kaggle) (6.0.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\prince raj\anaconda3\lib\site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.0)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\prince raj\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (2.20.0)
Requirement already satisfied: jsonschema>=2.6 in c:\users\prince raj\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (4.23.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\prince raj\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.7.2)
Requirement already satisfied: traitlets>=5.1 in c:\users\prince raj\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (24.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\prince raj\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\prince raj\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\prince raj\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.22.3)
Requirement already satisfied: platformdirs>=2.5 in c:\users\prince raj\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.3.7)
Requirement already satisfied: pywin32>=300 in c:\users\prince raj\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (308)
Requirement already satisfied: six>=1.5 in c:\users\prince raj\anaconda3\lib\site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\prince raj\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\prince raj\anaconda3\lib\site-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\prince raj\anaconda3\lib\site-packages (from requests->kaggle) (3.7)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\prince raj\anaconda3\lib\site-packages (from requests->kaggle) (2025.8.3)
Requirement already satisfied: colorama in c:\users\prince raj\anaconda3\lib\site-packages (from tqdm->kaggle) (0.4.6)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
# Cell 2 — Import Libraries

import kagglehub
import shutil
import os

In [6]:
# Cell 3 — Download Dataset

path = kagglehub.dataset_download(
    "thammuio/all-agriculture-related-datasets-for-india"
)

print("Original Dataset Path:")
print(path)

Original Dataset Path:
C:\Users\prince raj\.cache\kagglehub\datasets\thammuio\all-agriculture-related-datasets-for-india\versions\4

In [7]:
# Cell 4 — Create Your Project Dataset Folder

project_dataset_folder = r"C:\Users\prince raj\ChatBoat For Agriculture\datasets"

os.makedirs(project_dataset_folder, exist_ok=True)

print("Project dataset folder created")

Project dataset folder created

In [8]:
# Cell 5 — Copy Downloaded Dataset to Your Folder

shutil.copytree(
    path,
    project_dataset_folder,
    dirs_exist_ok=True
)

print("Dataset copied successfully")

Dataset copied successfully

In [9]:
# Cell 6 — Check All Files

for root, dirs, files in os.walk(project_dataset_folder):

    for file in files:

        print(os.path.join(root, file))

C:\Users\prince raj\ChatBoat For Agriculture\datasets\all-agriculture-related-datasets-for-india.zip
C:\Users\prince raj\ChatBoat For Agriculture\datasets\csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\csv.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\market_chatbot_data.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\.gradio\flagged\dataset1.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\.ipynb_checkpoints\csv-checkpoint
C:\Users\prince raj\ChatBoat For Agriculture\datasets\crop\Crop_recommendation.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\fertilizer\Fertilizer Prediction.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\final_data\agriculture_chatbot_dataset.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\smart_farming\Smart_Farming_Crop_Yield_2024.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\weather\weather_data.csv

In [10]:
# Cell 7 — Find All CSV Files

import glob

csv_files = glob.glob(
    r"C:\Users\prince raj\ChatBoat For Agriculture\datasets\**\*.csv",
    recursive=True
)

print("Total CSV Files Found:", len(csv_files))

for file in csv_files[:20]:
    print(file)

Total CSV Files Found: 7
C:\Users\prince raj\ChatBoat For Agriculture\datasets\csv.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\market_chatbot_data.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\crop\Crop_recommendation.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\fertilizer\Fertilizer Prediction.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\final_data\agriculture_chatbot_dataset.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\smart_farming\Smart_Farming_Crop_Yield_2024.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\weather\weather_data.csv

In [11]:
import pandas as pd

file_path = r"C:\Users\prince raj\ChatBoat For Agriculture\datasets\csv.csv"

df = pd.read_csv(file_path)

df.head()

,state,district,market,commodity,variety,arrival_date,min_price,max_price,modal_price
0,Andaman and Nicobar,South Andaman,Port Blair,Amaranthus,Amaranthus,04/03/2019,6000,8000,7000
1,Andaman and Nicobar,South Andaman,Port Blair,Banana - Green,Banana - Green,04/03/2019,4500,5500,5000
2,Andaman and Nicobar,South Andaman,Port Blair,Bhindi(Ladies Finger),Bhindi,04/03/2019,6000,8000,7000
3,Andaman and Nicobar,South Andaman,Port Blair,Bitter gourd,Other,04/03/2019,6000,8000,7000
4,Andaman and Nicobar,South Andaman,Port Blair,Black pepper,Other,04/03/2019,110000,130000,120000

In [12]:
print("Dataset Shape:")
print(df.shape)

print("\nColumns:")
print(df.columns)

print("\nDataset Info:")
df.info()

Dataset Shape:
(2238, 9)

Columns:
Index(['state', 'district', 'market', 'commodity', 'variety', 'arrival_date',
       'min_price', 'max_price', 'modal_price'],
      dtype='object')

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2238 entries, 0 to 2237
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state         2238 non-null   object
 1   district      2238 non-null   object
 2   market        2238 non-null   object
 3   commodity     2238 non-null   object
 4   variety       2238 non-null   object
 5   arrival_date  2238 non-null   object
 6   min_price     2238 non-null   int64
 7   max_price     2238 non-null   int64
 8   modal_price   2238 non-null   int64
dtypes: int64(3), object(6)
memory usage: 157.5+ KB

In [13]:
qa_data = []

for index, row in df.iterrows():

    commodity = row['commodity']
    state = row['state']
    district = row['district']
    market = row['market']
    variety = row['variety']

    min_price = row['min_price']
    max_price = row['max_price']
    modal_price = row['modal_price']

    arrival_date = row['arrival_date']

    # Question
    question = (
        f"What is the price of {commodity} "
        f"in {market} market of {district}, {state}?"
    )

    # Answer
    answer = (
        f"Commodity: {commodity}\n"
        f"Variety: {variety}\n"
        f"State: {state}\n"
        f"District: {district}\n"
        f"Market: {market}\n"
        f"Arrival Date: {arrival_date}\n"
        f"Minimum Price: ₹{min_price}\n"
        f"Maximum Price: ₹{max_price}\n"
        f"Modal Price: ₹{modal_price}"
    )

    qa_data.append([question, answer])

print("Question Answer Data Created")

Question Answer Data Created

In [14]:
qa_df = pd.DataFrame(
    qa_data,
    columns=["question", "answer"]
)

qa_df.head()

,question,answer
0,What is the price of Amaranthus in Port Blair ...,Commodity: Amaranthus\nVariety: Amaranthus\nSt...
1,What is the price of Banana - Green in Port Bl...,Commodity: Banana - Green\nVariety: Banana - G...
2,What is the price of Bhindi(Ladies Finger) in ...,Commodity: Bhindi(Ladies Finger)\nVariety: Bhi...
3,What is the price of Bitter gourd in Port Blai...,Commodity: Bitter gourd\nVariety: Other\nState...
4,What is the price of Black pepper in Port Blai...,Commodity: Black pepper\nVariety: Other\nState...

In [15]:
save_path = r"C:\Users\prince raj\ChatBoat For Agriculture\datasets\market_chatbot_data.csv"

qa_df.to_csv(save_path, index=False)

print("Chatbot dataset saved")

Chatbot dataset saved

In [16]:
!pip install sentence-transformers
!pip install scikit-learn

Requirement already satisfied: sentence-transformers in c:\users\prince raj\anaconda3\lib\site-packages (5.5.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sentence-transformers) (5.9.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sentence-transformers) (1.16.1)
Requirement already satisfied: torch>=1.11.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sentence-transformers) (2.12.0)
Requirement already satisfied: numpy>=1.20.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sentence-transformers) (2.1.3)
Requirement already satisfied: scikit-learn>=0.22.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sentence-transformers) (1.15.3)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: packaging>=20.0 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\prince raj\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: anyio in c:\users\prince raj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.7.0)
Requirement already satisfied: certifi in c:\users\prince raj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2025.8.3)
Requirement already satisfied: httpcore==1.* in c:\users\prince raj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\prince raj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.7)
Requirement already satisfied: h11>=0.16 in c:\users\prince raj\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\prince raj\anaconda3\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.5.0)
Requirement already satisfied: setuptools<82 in c:\users\prince raj\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (72.1.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\prince raj\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in c:\users\prince raj\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\prince raj\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in c:\users\prince raj\anaconda3\lib\site-packages (from tqdm>=4.0.0->sentence-transformers) (0.4.6)
Requirement already satisfied: click>=8.2.1 in c:\users\prince raj\anaconda3\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (8.4.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\prince raj\anaconda3\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.0)
Requirement already satisfied: rich>=13.8.0 in c:\users\prince raj\anaconda3\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\prince raj\anaconda3\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\prince raj\anaconda3\lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\prince raj\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\prince raj\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: scikit-learn in c:\users\prince raj\anaconda3\lib\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\prince raj\anaconda3\lib\site-packages (from scikit-learn) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in c:\users\prince raj\anaconda3\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\prince raj\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    'all-MiniLM-L6-v2'
)

print("AI Model Loaded")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

AI Model Loaded

In [18]:
questions = qa_df['question'].tolist()

question_embeddings = model.encode(
    questions,
    show_progress_bar=True
)

print("Embeddings Created")

Batches:   0%|          | 0/70 [00:00<?, ?it/s]

Embeddings Created

In [19]:
from sklearn.metrics.pairwise import cosine_similarity

import numpy as np

In [20]:
def agriculture_chatbot(user_query):

    query_embedding = model.encode([user_query])

    similarities = cosine_similarity(
        query_embedding,
        question_embeddings
    )

    best_match_index = np.argmax(similarities)

    response = qa_df.iloc[
        best_match_index
    ]['answer']

    return response

In [21]:
query = "What is tomato price in market?"

response = agriculture_chatbot(query)

print(response)

Commodity: Tomato
Variety: Tomato
State: Gujarat
District: Bharuch
Market: Ankleshwar
Arrival Date: 04/03/2019
Minimum Price: ₹750
Maximum Price: ₹1650
Modal Price: ₹1425

In [22]:
print("Agriculture Market Chatbot Started")
print("Type exit to stop")

while True:

    user_input = input("delhi ")

    if user_input.lower() == "exit":

        print("Chatbot Closed")

        break

    response = agriculture_chatbot(user_input)

    print("\nBot:\n")

    print(response)

    print("\n")

Agriculture Market Chatbot Started
Type exit to stop

delhi  exit

Chatbot Closed

In [23]:
!pip install gradio
!pip install sentence-transformers
!pip install scikit-learn
!pip install pandas
!pip install numpy
!pip install transformers
!pip install torch
!pip install kagglehub

Requirement already satisfied: gradio in c:\users\prince raj\anaconda3\lib\site-packages (6.15.1)
Requirement already satisfied: anyio<5.0,>=3.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (4.7.0)
Requirement already satisfied: audioop-lts<=0.2.2 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.2.2)
Requirement already satisfied: brotli>=1.1.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.136.3)
Requirement already satisfied: gradio-client==2.5.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (2.5.0)
Requirement already satisfied: groovy~=0.1 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.1.2)
Requirement already satisfied: hf-gradio<1.0,>=0.4.1 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.4.1)
Requirement already satisfied: httpx<1.0,>=0.24.1 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub<2.0,>=0.33.5 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (1.16.1)
Requirement already satisfied: jinja2<4.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (3.0.2)
Requirement already satisfied: numpy<3.0,>=1.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (2.1.3)
Requirement already satisfied: orjson~=3.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (3.11.9)
Requirement already satisfied: packaging in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (24.2)
Requirement already satisfied: pandas<4.0,>=1.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (2.2.3)
Requirement already satisfied: pillow<13.0,>=8.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (11.1.0)
Requirement already satisfied: pydantic<=3.0,>=2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (2.10.3)
Requirement already satisfied: pydub<1.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart<1.0,>=0.0.18 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.0.29)
Requirement already satisfied: pytz>=2017.2 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (2024.1)
Requirement already satisfied: pyyaml<7.0,>=5.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (6.0.2)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.7 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<2.0,>=0.40.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (1.2.0)
Requirement already satisfied: tomlkit<0.15.0,>=0.12.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.13.2)
Requirement already satisfied: typer<1.0,>=0.12 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.25.1)
Requirement already satisfied: typing-extensions~=4.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (4.15.0)
Requirement already satisfied: uvicorn>=0.14.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.48.0)
Requirement already satisfied: fsspec in c:\users\prince raj\anaconda3\lib\site-packages (from gradio-client==2.5.0->gradio) (2025.3.2)
Requirement already satisfied: idna>=2.8 in c:\users\prince raj\anaconda3\lib\site-packages (from anyio<5.0,>=3.0->gradio) (3.7)
Requirement already satisfied: sniffio>=1.1 in c:\users\prince raj\anaconda3\lib\site-packages (from anyio<5.0,>=3.0->gradio) (1.3.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\prince raj\anaconda3\lib\site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\prince raj\anaconda3\lib\site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.4)
Requirement already satisfied: certifi in c:\users\prince raj\anaconda3\lib\site-packages (from httpx<1.0,>=0.24.1->gradio) (2025.8.3)
Requirement already satisfied: httpcore==1.* in c:\users\prince raj\anaconda3\lib\site-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\prince raj\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (3.17.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (1.5.0)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (4.67.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\prince raj\anaconda3\lib\site-packages (from pandas<4.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\prince raj\anaconda3\lib\site-packages (from pandas<4.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\prince raj\anaconda3\lib\site-packages (from pydantic<=3.0,>=2.0->gradio) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in c:\users\prince raj\anaconda3\lib\site-packages (from pydantic<=3.0,>=2.0->gradio) (2.27.1)
Requirement already satisfied: click>=8.2.1 in c:\users\prince raj\anaconda3\lib\site-packages (from typer<1.0,>=0.12->gradio) (8.4.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\prince raj\anaconda3\lib\site-packages (from typer<1.0,>=0.12->gradio) (1.5.0)
Requirement already satisfied: rich>=13.8.0 in c:\users\prince raj\anaconda3\lib\site-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: colorama in c:\users\prince raj\anaconda3\lib\site-packages (from click>=8.2.1->typer<1.0,>=0.12->gradio) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\prince raj\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<4.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\prince raj\anaconda3\lib\site-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\prince raj\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0,>=0.12->gradio) (0.1.0)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: sentence-transformers in c:\users\prince raj\anaconda3\lib\site-packages (5.5.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sentence-transformers) (5.9.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sentence-transformers) (1.16.1)
Requirement already satisfied: torch>=1.11.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sentence-transformers) (2.12.0)
Requirement already satisfied: numpy>=1.20.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sentence-transformers) (2.1.3)
Requirement already satisfied: scikit-learn>=0.22.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sentence-transformers) (1.15.3)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: packaging>=20.0 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\prince raj\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: anyio in c:\users\prince raj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.7.0)
Requirement already satisfied: certifi in c:\users\prince raj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2025.8.3)
Requirement already satisfied: httpcore==1.* in c:\users\prince raj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\prince raj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.7)
Requirement already satisfied: h11>=0.16 in c:\users\prince raj\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\prince raj\anaconda3\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.5.0)
Requirement already satisfied: setuptools<82 in c:\users\prince raj\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (72.1.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\prince raj\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in c:\users\prince raj\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\prince raj\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in c:\users\prince raj\anaconda3\lib\site-packages (from tqdm>=4.0.0->sentence-transformers) (0.4.6)
Requirement already satisfied: click>=8.2.1 in c:\users\prince raj\anaconda3\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (8.4.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\prince raj\anaconda3\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.0)
Requirement already satisfied: rich>=13.8.0 in c:\users\prince raj\anaconda3\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\prince raj\anaconda3\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\prince raj\anaconda3\lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\prince raj\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\prince raj\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: scikit-learn in c:\users\prince raj\anaconda3\lib\site-packages (1.6.1)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy>=1.19.5 in c:\users\prince raj\anaconda3\lib\site-packages (from scikit-learn) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in c:\users\prince raj\anaconda3\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\prince raj\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: pandas in c:\users\prince raj\anaconda3\lib\site-packages (2.2.3)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy>=1.26.0 in c:\users\prince raj\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\prince raj\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\prince raj\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\prince raj\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\prince raj\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in c:\users\prince raj\anaconda3\lib\site-packages (2.1.3)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: transformers in c:\users\prince raj\anaconda3\lib\site-packages (5.9.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers) (1.16.1)
Requirement already satisfied: numpy>=1.17 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\prince raj\anaconda3\lib\site-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\prince raj\anaconda3\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: filelock>=3.10.0 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in c:\users\prince raj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.7.0)
Requirement already satisfied: certifi in c:\users\prince raj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2025.8.3)
Requirement already satisfied: httpcore==1.* in c:\users\prince raj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\prince raj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.7)
Requirement already satisfied: h11>=0.16 in c:\users\prince raj\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: colorama in c:\users\prince raj\anaconda3\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: click>=8.2.1 in c:\users\prince raj\anaconda3\lib\site-packages (from typer->transformers) (8.4.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\prince raj\anaconda3\lib\site-packages (from typer->transformers) (1.5.0)
Requirement already satisfied: rich>=13.8.0 in c:\users\prince raj\anaconda3\lib\site-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\prince raj\anaconda3\lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\prince raj\anaconda3\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\prince raj\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\prince raj\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: torch in c:\users\prince raj\anaconda3\lib\site-packages (2.12.0)
Requirement already satisfied: filelock in c:\users\prince raj\anaconda3\lib\site-packages (from torch) (3.17.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\prince raj\anaconda3\lib\site-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools<82 in c:\users\prince raj\anaconda3\lib\site-packages (from torch) (72.1.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\prince raj\anaconda3\lib\site-packages (from torch) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in c:\users\prince raj\anaconda3\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\prince raj\anaconda3\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\prince raj\anaconda3\lib\site-packages (from torch) (2025.3.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\prince raj\anaconda3\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from jinja2->torch) (3.0.2)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: kagglehub in c:\users\prince raj\anaconda3\lib\site-packages (1.0.1)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in c:\users\prince raj\anaconda3\lib\site-packages (from kagglehub) (0.1.23)
Requirement already satisfied: packaging in c:\users\prince raj\anaconda3\lib\site-packages (from kagglehub) (24.2)
Requirement already satisfied: pyyaml in c:\users\prince raj\anaconda3\lib\site-packages (from kagglehub) (6.0.2)
Requirement already satisfied: requests in c:\users\prince raj\anaconda3\lib\site-packages (from kagglehub) (2.34.2)
Requirement already satisfied: tqdm in c:\users\prince raj\anaconda3\lib\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in c:\users\prince raj\anaconda3\lib\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (6.33.6)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\prince raj\anaconda3\lib\site-packages (from requests->kagglehub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\prince raj\anaconda3\lib\site-packages (from requests->kagglehub) (3.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\prince raj\anaconda3\lib\site-packages (from requests->kagglehub) (2.3.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\prince raj\anaconda3\lib\site-packages (from requests->kagglehub) (2025.8.3)
Requirement already satisfied: colorama in c:\users\prince raj\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
import gradio
import pandas
import numpy
import sklearn
import torch
import transformers

print("All libraries installed successfully")

All libraries installed successfully

In [25]:
import kagglehub

weather_path = kagglehub.dataset_download(
    "prasad22/weather-data"
)

print(weather_path)

C:\Users\prince raj\.cache\kagglehub\datasets\prasad22\weather-data\versions\1

In [26]:
fertilizer_path = kagglehub.dataset_download(
    "gdabhishek/fertilizer-prediction"
)

print(fertilizer_path)

C:\Users\prince raj\.cache\kagglehub\datasets\gdabhishek\fertilizer-prediction\versions\1

In [27]:
crop_path = kagglehub.dataset_download(
    "atharvaingle/crop-recommendation-dataset"
)

print(crop_path)

C:\Users\prince raj\.cache\kagglehub\datasets\atharvaingle\crop-recommendation-dataset\versions\1

In [28]:
smart_farming_path = kagglehub.dataset_download(
    "atharvasoundankar/smart-farming-sensor-data-for-yield-prediction"
)

print(smart_farming_path)

C:\Users\prince raj\.cache\kagglehub\datasets\atharvasoundankar\smart-farming-sensor-data-for-yield-prediction\versions\1

In [29]:
import os

base_path = r"C:\Users\prince raj\ChatBoat For Agriculture"

folders = [
    "datasets/weather",
    "datasets/fertilizer",
    "datasets/crop",
    "datasets/smart_farming",
    "datasets/final_data",
    "models",
    "outputs",
    "app"
]

for folder in folders:
    
    os.makedirs(
        os.path.join(base_path, folder),
        exist_ok=True
    )

print("Project folders created successfully")

Project folders created successfully

In [30]:
import shutil

# Source Paths
weather_source = r"C:\Users\prince raj\.cache\kagglehub\datasets\prasad22\weather-data\versions\1"

fertilizer_source = r"C:\Users\prince raj\.cache\kagglehub\datasets\gdabhishek\fertilizer-prediction\versions\1"

crop_source = r"C:\Users\prince raj\.cache\kagglehub\datasets\atharvaingle\crop-recommendation-dataset\versions\1"

smart_source = r"C:\Users\prince raj\.cache\kagglehub\datasets\atharvasoundankar\smart-farming-sensor-data-for-yield-prediction\versions\1"

# Destination Paths
weather_dest = r"C:\Users\prince raj\ChatBoat For Agriculture\datasets\weather"

fertilizer_dest = r"C:\Users\prince raj\ChatBoat For Agriculture\datasets\fertilizer"

crop_dest = r"C:\Users\prince raj\ChatBoat For Agriculture\datasets\crop"

smart_dest = r"C:\Users\prince raj\ChatBoat For Agriculture\datasets\smart_farming"

# Copy datasets
shutil.copytree(weather_source, weather_dest, dirs_exist_ok=True)

shutil.copytree(fertilizer_source, fertilizer_dest, dirs_exist_ok=True)

shutil.copytree(crop_source, crop_dest, dirs_exist_ok=True)

shutil.copytree(smart_source, smart_dest, dirs_exist_ok=True)

print("All datasets copied successfully")

All datasets copied successfully

In [31]:
csv_files = glob.glob(
    r"C:\Users\prince raj\ChatBoat For Agriculture\datasets\**\*.csv",
    recursive=True
)

print("Total CSV Files:", len(csv_files))

for file in csv_files:
    
    print(file)

Total CSV Files: 7
C:\Users\prince raj\ChatBoat For Agriculture\datasets\csv.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\market_chatbot_data.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\crop\Crop_recommendation.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\fertilizer\Fertilizer Prediction.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\final_data\agriculture_chatbot_dataset.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\smart_farming\Smart_Farming_Crop_Yield_2024.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\weather\weather_data.csv

In [32]:
dataframes = []

for file in csv_files:
    
    try:
        
        df = pd.read_csv(file)
        
        df['source_file'] = os.path.basename(file)
        
        dataframes.append(df)
        
        print("Loaded:", file)
        
    except Exception as e:
        
        print("Error:", file)
        
        print(e)

Loaded: C:\Users\prince raj\ChatBoat For Agriculture\datasets\csv.csv
Loaded: C:\Users\prince raj\ChatBoat For Agriculture\datasets\market_chatbot_data.csv
Loaded: C:\Users\prince raj\ChatBoat For Agriculture\datasets\crop\Crop_recommendation.csv
Loaded: C:\Users\prince raj\ChatBoat For Agriculture\datasets\fertilizer\Fertilizer Prediction.csv
Loaded: C:\Users\prince raj\ChatBoat For Agriculture\datasets\final_data\agriculture_chatbot_dataset.csv
Loaded: C:\Users\prince raj\ChatBoat For Agriculture\datasets\smart_farming\Smart_Farming_Crop_Yield_2024.csv
Loaded: C:\Users\prince raj\ChatBoat For Agriculture\datasets\weather\weather_data.csv

In [33]:
qa_data = []

for df in dataframes:
    
    columns = list(df.columns)
    
    for index, row in df.head(1000).iterrows():
        
        question = ""
        
        answer = ""
        
        # Dynamic Question Creation
        if 'label' in columns:
            
            question = (
                f"Which crop is suitable "
                f"for soil and weather conditions?"
            )
            
        elif 'Temparature' in columns or 'Temperature' in columns:
            
            question = (
                f"What is the weather information?"
            )
            
        elif 'Fertilizer Name' in columns:
            
            question = (
                f"Which fertilizer should be used?"
            )
            
        else:
            
            question = (
                f"Give agriculture information"
            )
        
        # Dynamic Answer Creation
        for col in columns:
            
            answer += f"{col}: {row[col]}\n"
        
        qa_data.append([question, answer])

print("Unified QA Data Created")

print("Total QA Pairs:", len(qa_data))

Unified QA Data Created
Total QA Pairs: 5599

In [34]:
qa_df = pd.DataFrame(
    qa_data,
    columns=["question", "answer"]
)

qa_df.head()

,question,answer
0,Give agriculture information,state: Andaman and Nicobar\ndistrict: South An...
1,Give agriculture information,state: Andaman and Nicobar\ndistrict: South An...
2,Give agriculture information,state: Andaman and Nicobar\ndistrict: South An...
3,Give agriculture information,state: Andaman and Nicobar\ndistrict: South An...
4,Give agriculture information,state: Andaman and Nicobar\ndistrict: South An...

In [35]:
save_path = r"C:\Users\prince raj\ChatBoat For Agriculture\datasets\final_data\agriculture_chatbot_dataset.csv"

qa_df.to_csv(save_path, index=False)

print("Final chatbot dataset saved")

Final chatbot dataset saved

In [36]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    'all-MiniLM-L6-v2'
)

print("AI Model Loaded Successfully")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

AI Model Loaded Successfully

In [37]:
questions = qa_df['question'].tolist()

question_embeddings = model.encode(
    questions,
    show_progress_bar=True
)

print("Embeddings Created")

Batches:   0%|          | 0/175 [00:00<?, ?it/s]

Embeddings Created

In [38]:
from sklearn.metrics.pairwise import cosine_similarity

import numpy as np

In [39]:
def agriculture_chatbot(user_query):
    
    query_embedding = model.encode([user_query])
    
    similarities = cosine_similarity(
        query_embedding,
        question_embeddings
    )
    
    best_match_index = np.argmax(similarities)
    
    response = qa_df.iloc[
        best_match_index
    ]['answer']
    
    return response

In [40]:
query = "Best fertilizer for crops"

response = agriculture_chatbot(query)

print(response)

N: 90
P: 42
K: 43
temperature: 20.87974371
humidity: 82.00274423
ph: 6.502985292000001
rainfall: 202.9355362
label: rice
source_file: Crop_recommendation.csv

In [41]:
print("Agriculture AI Chatbot Started")
print("Type exit to stop")

while True:
    
    user_input = input("You: ")
    
    if user_input.lower() == "exit":
        
        print("Chatbot Closed")
        
        break
    
    response = agriculture_chatbot(user_input)
    
    print("\nBot:\n")
    
    print(response)
    
    print("\n")

Agriculture AI Chatbot Started
Type exit to stop

You:  exit

Chatbot Closed

In [42]:
!pip install gradio

Requirement already satisfied: gradio in c:\users\prince raj\anaconda3\lib\site-packages (6.15.1)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: anyio<5.0,>=3.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (4.7.0)
Requirement already satisfied: audioop-lts<=0.2.2 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.2.2)
Requirement already satisfied: brotli>=1.1.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.136.3)
Requirement already satisfied: gradio-client==2.5.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (2.5.0)
Requirement already satisfied: groovy~=0.1 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.1.2)
Requirement already satisfied: hf-gradio<1.0,>=0.4.1 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.4.1)
Requirement already satisfied: httpx<1.0,>=0.24.1 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub<2.0,>=0.33.5 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (1.16.1)
Requirement already satisfied: jinja2<4.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (3.0.2)
Requirement already satisfied: numpy<3.0,>=1.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (2.1.3)
Requirement already satisfied: orjson~=3.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (3.11.9)
Requirement already satisfied: packaging in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (24.2)
Requirement already satisfied: pandas<4.0,>=1.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (2.2.3)
Requirement already satisfied: pillow<13.0,>=8.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (11.1.0)
Requirement already satisfied: pydantic<=3.0,>=2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (2.10.3)
Requirement already satisfied: pydub<1.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart<1.0,>=0.0.18 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.0.29)
Requirement already satisfied: pytz>=2017.2 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (2024.1)
Requirement already satisfied: pyyaml<7.0,>=5.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (6.0.2)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.7 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<2.0,>=0.40.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (1.2.0)
Requirement already satisfied: tomlkit<0.15.0,>=0.12.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.13.2)
Requirement already satisfied: typer<1.0,>=0.12 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.25.1)
Requirement already satisfied: typing-extensions~=4.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (4.15.0)
Requirement already satisfied: uvicorn>=0.14.0 in c:\users\prince raj\anaconda3\lib\site-packages (from gradio) (0.48.0)
Requirement already satisfied: fsspec in c:\users\prince raj\anaconda3\lib\site-packages (from gradio-client==2.5.0->gradio) (2025.3.2)
Requirement already satisfied: idna>=2.8 in c:\users\prince raj\anaconda3\lib\site-packages (from anyio<5.0,>=3.0->gradio) (3.7)
Requirement already satisfied: sniffio>=1.1 in c:\users\prince raj\anaconda3\lib\site-packages (from anyio<5.0,>=3.0->gradio) (1.3.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\prince raj\anaconda3\lib\site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\prince raj\anaconda3\lib\site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.4)
Requirement already satisfied: certifi in c:\users\prince raj\anaconda3\lib\site-packages (from httpx<1.0,>=0.24.1->gradio) (2025.8.3)
Requirement already satisfied: httpcore==1.* in c:\users\prince raj\anaconda3\lib\site-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\prince raj\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (3.17.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (1.5.0)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\prince raj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (4.67.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\prince raj\anaconda3\lib\site-packages (from pandas<4.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\prince raj\anaconda3\lib\site-packages (from pandas<4.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\prince raj\anaconda3\lib\site-packages (from pydantic<=3.0,>=2.0->gradio) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in c:\users\prince raj\anaconda3\lib\site-packages (from pydantic<=3.0,>=2.0->gradio) (2.27.1)
Requirement already satisfied: click>=8.2.1 in c:\users\prince raj\anaconda3\lib\site-packages (from typer<1.0,>=0.12->gradio) (8.4.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\prince raj\anaconda3\lib\site-packages (from typer<1.0,>=0.12->gradio) (1.5.0)
Requirement already satisfied: rich>=13.8.0 in c:\users\prince raj\anaconda3\lib\site-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: colorama in c:\users\prince raj\anaconda3\lib\site-packages (from click>=8.2.1->typer<1.0,>=0.12->gradio) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\prince raj\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<4.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\prince raj\anaconda3\lib\site-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\prince raj\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0,>=0.12->gradio) (0.1.0)

In [43]:
import gradio as gr

interface = gr.Interface(
    fn=agriculture_chatbot,
    
    inputs=gr.Textbox(
        placeholder="Ask agriculture related questions..."
    ),
    
    outputs="text",
    
    title="Agriculture AI Chatbot",
    
    description=(
        "AI chatbot for crop recommendation, "
        "weather, fertilizer, and smart farming"
    )
)

interface.launch()

* Running on local URL:  http://127.0.0.1:7861
* To create a public link, set `share=True` in `launch()`.

Traceback (most recent call last):
  File "C:\Users\prince raj\anaconda3\Lib\site-packages\gradio\queueing.py", line 867, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "C:\Users\prince raj\anaconda3\Lib\site-packages\gradio\route_utils.py", line 386, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
    )
    ^
  File "C:\Users\prince raj\anaconda3\Lib\site-packages\gradio\blocks.py", line 2195, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<8 lines>...
    )
    ^
  File "C:\Users\prince raj\anaconda3\Lib\site-packages\gradio\blocks.py", line 1652, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        fn, *processed_input, limiter=self.limiter
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\prince raj\anaconda3\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\prince raj\anaconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\prince raj\anaconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "C:\Users\prince raj\anaconda3\Lib\site-packages\gradio\utils.py", line 1061, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\prince raj\AppData\Local\Temp\ipykernel_19248\4022813975.py", line 12, in agriculture_chatbot
    response = qa_df.iloc[
               ~~~~~~~~~~^
        best_match_index
        ^^^^^^^^^^^^^^^^
    ]['answer']
    ^
  File "C:\Users\prince raj\anaconda3\Lib\site-packages\pandas\core\indexing.py", line 1191, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prince raj\anaconda3\Lib\site-packages\pandas\core\indexing.py", line 1752, in _getitem_axis
    self._validate_integer(key, axis)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\prince raj\anaconda3\Lib\site-packages\pandas\core\indexing.py", line 1685, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

In [44]:
import pandas as pd

# Load market chatbot dataset
qa_df = pd.read_csv(
    r"C:\Users\prince raj\ChatBoat For Agriculture\datasets\market_chatbot_data.csv"
)

# Save final dataset
qa_df.to_csv(
    r"C:\Users\prince raj\ChatBoat For Agriculture\huggingface_app\agriculture_chatbot_dataset.csv",
    index=False
)

print("Final dataset ready")

Final dataset ready

In [45]:
import pandas as pd
import numpy as np
import glob
import os

In [46]:
csv_files = glob.glob(
    r"C:\Users\prince raj\ChatBoat For Agriculture\datasets\**\*.csv",
    recursive=True
)

print("Total CSV Files:", len(csv_files))

for file in csv_files:
    
    print(file)

Total CSV Files: 7
C:\Users\prince raj\ChatBoat For Agriculture\datasets\csv.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\market_chatbot_data.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\crop\Crop_recommendation.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\fertilizer\Fertilizer Prediction.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\final_data\agriculture_chatbot_dataset.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\smart_farming\Smart_Farming_Crop_Yield_2024.csv
C:\Users\prince raj\ChatBoat For Agriculture\datasets\weather\weather_data.csv

In [47]:
dataframes = []

for file in csv_files:
    
    try:
        
        df = pd.read_csv(file)
        
        df['source_file'] = os.path.basename(file)
        
        dataframes.append(df)
        
        print("Loaded:", file)
        
    except Exception as e:
        
        print("Error loading:", file)
        
        print(e)

Loaded: C:\Users\prince raj\ChatBoat For Agriculture\datasets\csv.csv
Loaded: C:\Users\prince raj\ChatBoat For Agriculture\datasets\market_chatbot_data.csv
Loaded: C:\Users\prince raj\ChatBoat For Agriculture\datasets\crop\Crop_recommendation.csv
Loaded: C:\Users\prince raj\ChatBoat For Agriculture\datasets\fertilizer\Fertilizer Prediction.csv
Loaded: C:\Users\prince raj\ChatBoat For Agriculture\datasets\final_data\agriculture_chatbot_dataset.csv
Loaded: C:\Users\prince raj\ChatBoat For Agriculture\datasets\smart_farming\Smart_Farming_Crop_Yield_2024.csv
Loaded: C:\Users\prince raj\ChatBoat For Agriculture\datasets\weather\weather_data.csv

In [48]:
qa_data = []

for df in dataframes:
    
    columns = list(df.columns)

    for index, row in df.head(3000).iterrows():

        answer = ""

        # =========================================
        # WEATHER DATASET
        # =========================================
        
        if (
            'Temperature' in columns or
            'Temparature' in columns or
            'Humidity' in columns
        ):

            question = (
                f"What is the weather information?"
            )

        # =========================================
        # CROP RECOMMENDATION
        # =========================================

        elif (
            'label' in columns or
            'N' in columns and
            'P' in columns and
            'K' in columns
        ):

            question = (
                f"Which crop is suitable "
                f"for this soil condition?"
            )

        # =========================================
        # FERTILIZER DATASET
        # =========================================

        elif (
            'Fertilizer Name' in columns or
            'Fertilizer' in columns
        ):

            question = (
                f"Which fertilizer should I use?"
            )

        # =========================================
        # MARKET PRICE DATASET
        # =========================================

        elif (
            'commodity' in columns or
            'modal_price' in columns
        ):

            commodity = row.get(
                'commodity',
                'crop'
            )

            question = (
                f"What is the market price "
                f"of {commodity}?"
            )

        # =========================================
        # SMART FARMING DATASET
        # =========================================

        else:

            question = (
                f"Give smart farming information"
            )

        # =========================================
        # CREATE DETAILED ANSWER
        # =========================================

        for col in columns:

            answer += (
                f"{col}: {row[col]}\n"
            )

        qa_data.append([
            question,
            answer
        ])

print("FINAL QA DATA CREATED")

print("Total QA Pairs:", len(qa_data))

FINAL QA DATA CREATED
Total QA Pairs: 13275

In [49]:
qa_df = pd.DataFrame(
    qa_data,
    columns=["question", "answer"]
)

qa_df.head()

,question,answer
0,What is the market price of Amaranthus?,state: Andaman and Nicobar\ndistrict: South An...
1,What is the market price of Banana - Green?,state: Andaman and Nicobar\ndistrict: South An...
2,What is the market price of Bhindi(Ladies Fing...,state: Andaman and Nicobar\ndistrict: South An...
3,What is the market price of Bitter gourd?,state: Andaman and Nicobar\ndistrict: South An...
4,What is the market price of Black pepper?,state: Andaman and Nicobar\ndistrict: South An...

In [50]:
qa_df = pd.DataFrame(
    qa_data,
    columns=["question", "answer"]
)

qa_df.tail()

,question,answer
13270,Give smart farming information,Location: Dallas\nDate_Time: 2024-02-16 02:52:...
13271,Give smart farming information,Location: Chicago\nDate_Time: 2024-02-08 09:59...
13272,Give smart farming information,Location: Los Angeles\nDate_Time: 2024-03-29 0...
13273,Give smart farming information,Location: New York\nDate_Time: 2024-02-20 17:2...
13274,Give smart farming information,Location: Chicago\nDate_Time: 2024-04-22 20:28...

In [51]:
save_path = (
    r"C:\Users\prince raj\ChatBoat For Agriculture"
    r"\huggingface_app"
    r"\agriculture_chatbot_dataset.csv"
)

qa_df.to_csv(
    save_path,
    index=False
)

print("FINAL AGRICULTURE DATASET SAVED")

FINAL AGRICULTURE DATASET SAVED

In [52]:
print(qa_df.shape)

qa_df.sample(10)

(13275, 2)

,question,answer
138,What is the market price of Paddy(Dhan)(Common)?,state: Gujarat\ndistrict: Surat\nmarket: Mandv...
10896,Give smart farming information,Location: San Antonio\nDate_Time: 2024-04-13 1...
11297,Give smart farming information,Location: Phoenix\nDate_Time: 2024-05-05 22:14...
457,What is the market price of Cowpea(Veg)?,state: Kerala\ndistrict: Kasargod\nmarket: Kas...
12755,Give smart farming information,Location: San Antonio\nDate_Time: 2024-01-11 2...
9224,Give smart farming information,question: Which crop is suitable for soil and ...
4709,Which crop is suitable for this soil condition?,N: 22\nP: 78\nK: 76\ntemperature: 17.84851658\...
4525,Which crop is suitable for this soil condition?,N: 88\nP: 55\nK: 45\ntemperature: 24.63544858\...
6819,Give smart farming information,question: Give agriculture information\nanswer...
11971,Give smart farming information,Location: Houston\nDate_Time: 2024-04-25 08:52...

In [53]:
csv_files = glob.glob(
    r"C:\Users\prince raj\ChatBoat For Agriculture\datasets\**\*.csv",
    recursive=True
)

print(csv_files)

['C:\\Users\\prince raj\\ChatBoat For Agriculture\\datasets\\csv.csv', 'C:\\Users\\prince raj\\ChatBoat For Agriculture\\datasets\\market_chatbot_data.csv', 'C:\\Users\\prince raj\\ChatBoat For Agriculture\\datasets\\crop\\Crop_recommendation.csv', 'C:\\Users\\prince raj\\ChatBoat For Agriculture\\datasets\\fertilizer\\Fertilizer Prediction.csv', 'C:\\Users\\prince raj\\ChatBoat For Agriculture\\datasets\\final_data\\agriculture_chatbot_dataset.csv', 'C:\\Users\\prince raj\\ChatBoat For Agriculture\\datasets\\smart_farming\\Smart_Farming_Crop_Yield_2024.csv', 'C:\\Users\\prince raj\\ChatBoat For Agriculture\\datasets\\weather\\weather_data.csv']

In [54]:
dataframes = []

for file in csv_files:

    try:

        df = pd.read_csv(file)

        df['source_file'] = os.path.basename(file)

        dataframes.append(df)

        print("Loaded:", file)

    except Exception as e:

        print(e)

Loaded: C:\Users\prince raj\ChatBoat For Agriculture\datasets\csv.csv
Loaded: C:\Users\prince raj\ChatBoat For Agriculture\datasets\market_chatbot_data.csv
Loaded: C:\Users\prince raj\ChatBoat For Agriculture\datasets\crop\Crop_recommendation.csv
Loaded: C:\Users\prince raj\ChatBoat For Agriculture\datasets\fertilizer\Fertilizer Prediction.csv
Loaded: C:\Users\prince raj\ChatBoat For Agriculture\datasets\final_data\agriculture_chatbot_dataset.csv
Loaded: C:\Users\prince raj\ChatBoat For Agriculture\datasets\smart_farming\Smart_Farming_Crop_Yield_2024.csv
Loaded: C:\Users\prince raj\ChatBoat For Agriculture\datasets\weather\weather_data.csv

In [55]:
qa_data = []

for df in dataframes:

    columns = list(df.columns)

    for index, row in df.head(2000).iterrows():

        answer = ""

        # =========================================
        # MARKET PRICE DATASET
        # =========================================

        if (
            'commodity' in columns and
            'modal_price' in columns
        ):

            commodity = row.get('commodity', '')

            state = row.get('state', '')

            market = row.get('market', '')

            question = (
                f"What is the price of "
                f"{commodity} in {market} market?"
            )

        # =========================================
        # CROP RECOMMENDATION DATASET
        # =========================================

        elif (
            'N' in columns and
            'P' in columns and
            'K' in columns and
            'label' in columns
        ):

            question = (
                f"Which crop grows best "
                f"with NPK values "
                f"{row['N']}, {row['P']}, {row['K']}?"
            )

        # =========================================
        # FERTILIZER DATASET
        # =========================================

        elif (
            'Fertilizer Name' in columns
        ):

            crop = row.get('Crop Type', '')

            soil = row.get('Soil Type', '')

            question = (
                f"Best fertilizer for "
                f"{crop} crop in {soil} soil?"
            )

        # =========================================
        # WEATHER DATASET
        # =========================================

        elif (
            'Temperature' in columns or
            'Temparature' in columns
        ):

            temp = row.get(
                'Temperature',
                row.get('Temparature', '')
            )

            humidity = row.get(
                'Humidity',
                ''
            )

            question = (
                f"What weather has "
                f"temperature {temp} "
                f"and humidity {humidity}?"
            )

        # =========================================
        # SMART FARMING
        # =========================================

        else:

            question = (
                "Give smart farming advice"
            )

        # =========================================
        # CREATE ANSWER
        # =========================================

        for col in columns:

            answer += (
                f"{col}: {row[col]}\n"
            )

        qa_data.append([
            question,
            answer
        ])

print("SMART QA DATASET CREATED")

print("Total QA:", len(qa_data))

SMART QA DATASET CREATED
Total QA: 10599

In [56]:
qa_df = pd.DataFrame(
    qa_data,
    columns=["question", "answer"]
)

qa_df.head()

,question,answer
0,What is the price of Amaranthus in Port Blair ...,state: Andaman and Nicobar\ndistrict: South An...
1,What is the price of Banana - Green in Port Bl...,state: Andaman and Nicobar\ndistrict: South An...
2,What is the price of Bhindi(Ladies Finger) in ...,state: Andaman and Nicobar\ndistrict: South An...
3,What is the price of Bitter gourd in Port Blai...,state: Andaman and Nicobar\ndistrict: South An...
4,What is the price of Black pepper in Port Blai...,state: Andaman and Nicobar\ndistrict: South An...

In [57]:
save_path = (
    r"C:\Users\prince raj\ChatBoat For Agriculture"
    r"\huggingface_app"
    r"\agriculture_chatbot_dataset.csv"
)

qa_df.to_csv(
    save_path,
    index=False
)

print("NEW SMART DATASET SAVED")

NEW SMART DATASET SAVED